package com.mcit.schoolmis.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ExamSubjectAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExamSubjectAllPropertiesEquals(ExamSubject expected, ExamSubject actual) {
        assertExamSubjectAutoGeneratedPropertiesEquals(expected, actual);
        assertExamSubjectAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExamSubjectAllUpdatablePropertiesEquals(ExamSubject expected, ExamSubject actual) {
        assertExamSubjectUpdatableFieldsEquals(expected, actual);
        assertExamSubjectUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExamSubjectAutoGeneratedPropertiesEquals(ExamSubject expected, ExamSubject actual) {
        assertThat(expected)
            .as("Verify ExamSubject auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExamSubjectUpdatableFieldsEquals(ExamSubject expected, ExamSubject actual) {
        assertThat(expected)
            .as("Verify ExamSubject relevant properties")
            .satisfies(e -> assertThat(e.getMaxMarks()).as("check maxMarks").isEqualTo(actual.getMaxMarks()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExamSubjectUpdatableRelationshipsEquals(ExamSubject expected, ExamSubject actual) {
        assertThat(expected)
            .as("Verify ExamSubject relationships")
            .satisfies(e -> assertThat(e.getExam()).as("check exam").isEqualTo(actual.getExam()))
            .satisfies(e -> assertThat(e.getSubject()).as("check subject").isEqualTo(actual.getSubject()));
    }
}
