package com.mcit.schoolmis.domain;

import static com.mcit.schoolmis.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class FeeStructureAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeeStructureAllPropertiesEquals(FeeStructure expected, FeeStructure actual) {
        assertFeeStructureAutoGeneratedPropertiesEquals(expected, actual);
        assertFeeStructureAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeeStructureAllUpdatablePropertiesEquals(FeeStructure expected, FeeStructure actual) {
        assertFeeStructureUpdatableFieldsEquals(expected, actual);
        assertFeeStructureUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeeStructureAutoGeneratedPropertiesEquals(FeeStructure expected, FeeStructure actual) {
        assertThat(expected)
            .as("Verify FeeStructure auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeeStructureUpdatableFieldsEquals(FeeStructure expected, FeeStructure actual) {
        assertThat(expected)
            .as("Verify FeeStructure relevant properties")
            .satisfies(e -> assertThat(e.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getAmount()))
            .satisfies(e -> assertThat(e.getAcademicYear()).as("check academicYear").isEqualTo(actual.getAcademicYear()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeeStructureUpdatableRelationshipsEquals(FeeStructure expected, FeeStructure actual) {
        assertThat(expected)
            .as("Verify FeeStructure relationships")
            .satisfies(e -> assertThat(e.getStudentClass()).as("check studentClass").isEqualTo(actual.getStudentClass()));
    }
}
