package com.mcit.schoolmis.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SectionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSectionAllPropertiesEquals(Section expected, Section actual) {
        assertSectionAutoGeneratedPropertiesEquals(expected, actual);
        assertSectionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSectionAllUpdatablePropertiesEquals(Section expected, Section actual) {
        assertSectionUpdatableFieldsEquals(expected, actual);
        assertSectionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSectionAutoGeneratedPropertiesEquals(Section expected, Section actual) {
        assertThat(expected)
            .as("Verify Section auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSectionUpdatableFieldsEquals(Section expected, Section actual) {
        assertThat(expected)
            .as("Verify Section relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSectionUpdatableRelationshipsEquals(Section expected, Section actual) {
        assertThat(expected)
            .as("Verify Section relationships")
            .satisfies(e -> assertThat(e.getStudentClass()).as("check studentClass").isEqualTo(actual.getStudentClass()));
    }
}
