package com.mcit.schoolmis.domain;

import static com.mcit.schoolmis.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class StudentResultAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentResultAllPropertiesEquals(StudentResult expected, StudentResult actual) {
        assertStudentResultAutoGeneratedPropertiesEquals(expected, actual);
        assertStudentResultAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentResultAllUpdatablePropertiesEquals(StudentResult expected, StudentResult actual) {
        assertStudentResultUpdatableFieldsEquals(expected, actual);
        assertStudentResultUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentResultAutoGeneratedPropertiesEquals(StudentResult expected, StudentResult actual) {
        assertThat(expected)
            .as("Verify StudentResult auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentResultUpdatableFieldsEquals(StudentResult expected, StudentResult actual) {
        assertThat(expected)
            .as("Verify StudentResult relevant properties")
            .satisfies(
                e ->
                    assertThat(e.getMarksObtained())
                        .as("check marksObtained")
                        .usingComparator(bigDecimalCompareTo)
                        .isEqualTo(actual.getMarksObtained())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentResultUpdatableRelationshipsEquals(StudentResult expected, StudentResult actual) {
        assertThat(expected)
            .as("Verify StudentResult relationships")
            .satisfies(e -> assertThat(e.getStudent()).as("check student").isEqualTo(actual.getStudent()))
            .satisfies(e -> assertThat(e.getExamSubject()).as("check examSubject").isEqualTo(actual.getExamSubject()));
    }
}
