package com.mcit.schoolmis.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TeacherSubjectAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTeacherSubjectAllPropertiesEquals(TeacherSubject expected, TeacherSubject actual) {
        assertTeacherSubjectAutoGeneratedPropertiesEquals(expected, actual);
        assertTeacherSubjectAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTeacherSubjectAllUpdatablePropertiesEquals(TeacherSubject expected, TeacherSubject actual) {
        assertTeacherSubjectUpdatableFieldsEquals(expected, actual);
        assertTeacherSubjectUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTeacherSubjectAutoGeneratedPropertiesEquals(TeacherSubject expected, TeacherSubject actual) {
        assertThat(expected)
            .as("Verify TeacherSubject auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTeacherSubjectUpdatableFieldsEquals(TeacherSubject expected, TeacherSubject actual) {}

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTeacherSubjectUpdatableRelationshipsEquals(TeacherSubject expected, TeacherSubject actual) {
        assertThat(expected)
            .as("Verify TeacherSubject relationships")
            .satisfies(e -> assertThat(e.getTeacher()).as("check teacher").isEqualTo(actual.getTeacher()))
            .satisfies(e -> assertThat(e.getSubject()).as("check subject").isEqualTo(actual.getSubject()))
            .satisfies(e -> assertThat(e.getSection()).as("check section").isEqualTo(actual.getSection()));
    }
}
